version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./api:/app
    ports:
      - "3001:3001"
    environment:
      - MOVIES_API_KEY=${MOVIES_API_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client:/app
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    depends_on:
      - api
      - client
    ports:
      - "8080:80"
  redis:
    image: 'redis:latest'